In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('Placement.csv')

In [3]:
import warnings

In [4]:
warnings.filterwarnings('ignore')

### 1. Display Top 5 Rows of The Dataset

In [5]:
data.head()

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0

### 2. Check Last 5 Rows of The Dataset

In [6]:
data.tail()

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
210,211,M,80.6,Others,82.0,Others,Commerce,77.6,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.0,Others,60.0,Others,Science,72.0,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.0,Others,67.0,Others,Commerce,73.0,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.0,Others,66.0,Others,Commerce,58.0,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.0,Central,58.0,Others,Science,53.0,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,NaN

### 3. Find Shape of Our Dataset (Number of Rows And Number of Columns)

In [7]:
data.shape

(215, 15)

In [8]:
print("Number of Rows",data.shape[0])
print("Number of Columns",data.shape[1])

Number of Rows 215
Number of Columns 15

### 4. Get Information About Our Dataset Like the Total Number of Rows, Total Number of Columns, Datatypes of Each Column And Memory Requirement

In [9]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           215 non-null    int64
 1   gender          215 non-null    str
 2   ssc_p           215 non-null    float64
 3   ssc_b           215 non-null    str
 4   hsc_p           215 non-null    float64
 5   hsc_b           215 non-null    str
 6   hsc_s           215 non-null    str
 7   degree_p        215 non-null    float64
 8   degree_t        215 non-null    str
 9   workex          215 non-null    str
 10  etest_p         215 non-null    float64
 11  specialisation  215 non-null    str
 12  mba_p           215 non-null    float64
 13  status          215 non-null    str
 14  salary          148 non-null    float64
dtypes: float64(6), int64(1), str(8)
memory usage: 25.3 KB

### 5. Check Null Values In The Dataset

In [10]:
data.isnull().sum()

sl_no              0
gender             0
ssc_p              0
ssc_b              0
hsc_p              0
hsc_b              0
hsc_s              0
degree_p           0
degree_t           0
workex             0
etest_p            0
specialisation     0
mba_p              0
status             0
salary            67
dtype: int64

### 6. Get Overall Statistics About The Dataset

In [11]:
data.describe()

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
count,215.000000,215.000000,215.000000,215.000000,215.000000,215.000000,148.000000
mean,108.000000,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
std,62.209324,10.827205,10.897509,7.358743,13.275956,5.833385,93457.452420
min,1.000000,40.890000,37.000000,50.000000,50.000000,51.210000,200000.000000
25%,54.500000,60.600000,60.900000,61.000000,60.000000,57.945000,240000.000000
50%,108.000000,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
75%,161.500000,75.700000,73.000000,72.000000,83.500000,66.255000,300000.000000
max,215.000000,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000

### 7. EDA

In [12]:
data.columns

Index(['sl_no', 'gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s',
       'degree_p', 'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p',
       'status', 'salary'],
      dtype='str')

#### How Many Students Got Placed?

In [13]:
data['status'].unique()

<StringArray>
['Placed', 'Not Placed']
Length: 2, dtype: str

In [14]:
data['status'].value_counts()

status
Placed        148
Not Placed     67
Name: count, dtype: int64

#### Could you display the top 5 sci&tech students placed according to their salary?

In [15]:
data.columns

Index(['sl_no', 'gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s',
       'degree_p', 'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p',
       'status', 'salary'],
      dtype='str')

In [16]:
data[(data['degree_t']=="Sci&Tech") & (data['status']=="Placed")].sort_values(by="salary",ascending=False).head()

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
150,151,M,71.00,Central,58.66,Central,Science,58.00,Sci&Tech,Yes,56.0,Mkt&Fin,61.30,Placed,690000.0
174,175,M,73.24,Others,50.83,Others,Science,64.27,Sci&Tech,Yes,64.0,Mkt&Fin,66.23,Placed,500000.0
163,164,M,63.00,Others,67.00,Others,Science,64.00,Sci&Tech,No,75.0,Mkt&Fin,66.46,Placed,500000.0
77,78,M,64.00,Others,80.00,Others,Science,65.00,Sci&Tech,Yes,69.0,Mkt&Fin,57.65,Placed,500000.0
53,54,M,80.00,Others,70.00,Others,Science,72.00,Sci&Tech,No,87.0,Mkt&HR,71.04,Placed,450000.0

### 8. Data Preprocessing

In [17]:
data.head()

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,NaN
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0

In [18]:
data = data.drop(['sl_no','salary'],axis=1)

In [19]:
data.head(1)

,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status
0,M,67.0,Others,91.0,Others,Commerce,58.0,Sci&Tech,No,55.0,Mkt&HR,58.8,Placed

#### Encoding the Categorical Columns

In [20]:
# Diagnostic: check all columns still containing strings before encoding
print('Column dtypes:')
print(data.dtypes)
print('\nUnique values in each non-numeric column:')
for col in data.select_dtypes(include='object').columns:
    print(f'  {col}: {data[col].unique()}')

Column dtypes:
gender                str
ssc_p             float64
ssc_b                 str
hsc_p             float64
hsc_b                 str
hsc_s                 str
degree_p          float64
degree_t              str
workex                str
etest_p           float64
specialisation        str
mba_p             float64
status                str
dtype: object

Unique values in each non-numeric column:
  gender: <StringArray>
['M', 'F']
Length: 2, dtype: str
  ssc_b: <StringArray>
['Others', 'Central']
Length: 2, dtype: str
  hsc_b: <StringArray>
['Others', 'Central']
Length: 2, dtype: str
  hsc_s: <StringArray>
['Commerce', 'Science', 'Arts']
Length: 3, dtype: str
  degree_t: <StringArray>
['Sci&Tech', 'Comm&Mgmt', 'Others']
Length: 3, dtype: str
  workex: <StringArray>
['No', 'Yes']
Length: 2, dtype: str
  specialisation: <StringArray>
['Mkt&HR', 'Mkt&Fin']
Length: 2, dtype: str
  status: <StringArray>
['Placed', 'Not Placed']
Length: 2, dtype: str

##### Encode Gender Column (M/F → 1/0)

In [21]:
# Encode gender: handles both 'M'/'F' strings AND already-numeric 0/1
if data['gender'].dtype == object:
    data['gender'] = data['gender'].map({'M': 1, 'F': 0})
    print('Gender encoded: M→1, F→0')
else:
    print('Gender already numeric, no encoding needed')
print(data['gender'].unique())

Gender already numeric, no encoding needed
<StringArray>
['M', 'F']
Length: 2, dtype: str

In [22]:
data['ssc_b'].unique()

<StringArray>
['Others', 'Central']
Length: 2, dtype: str

In [23]:
data['ssc_b'] = data['ssc_b'].map({'Central':1,'Others':0})

In [24]:
data.head(2)

,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status
0,M,67.00,0,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed
1,M,79.33,1,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed

In [25]:
data['hsc_b'].unique()

<StringArray>
['Others', 'Central']
Length: 2, dtype: str

In [26]:
data['hsc_b'] = data['hsc_b'].map({'Central':1,'Others':0})

In [27]:
data.head(2)

,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status
0,M,67.00,0,91.00,0,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed
1,M,79.33,1,78.33,0,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed

In [28]:
data['hsc_s'].unique()

<StringArray>
['Commerce', 'Science', 'Arts']
Length: 3, dtype: str

In [29]:
data['hsc_s'] = data['hsc_s'].map({'Science':2,'Commerce':1,'Arts':0})

In [30]:
data.head()

,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status
0,M,67.00,0,91.00,0,1,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed
1,M,79.33,1,78.33,0,2,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed
2,M,65.00,1,68.00,1,0,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed
3,M,56.00,1,52.00,1,2,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed
4,M,85.80,1,73.60,1,1,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed

In [31]:
data['degree_t'].unique()

<StringArray>
['Sci&Tech', 'Comm&Mgmt', 'Others']
Length: 3, dtype: str

In [32]:
data['degree_t'] = data['degree_t'].map({'Sci&Tech':2,'Comm&Mgmt':1,'Others':0})

In [33]:
data.head(2)

,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status
0,M,67.00,0,91.00,0,1,58.00,2,No,55.0,Mkt&HR,58.80,Placed
1,M,79.33,1,78.33,0,2,77.48,2,Yes,86.5,Mkt&Fin,66.28,Placed

In [34]:
data['specialisation'].unique()

<StringArray>
['Mkt&HR', 'Mkt&Fin']
Length: 2, dtype: str

In [35]:
data['specialisation'] =data['specialisation'].map({'Mkt&HR':1,'Mkt&Fin':0})

In [36]:
data.head(2)

,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status
0,M,67.00,0,91.00,0,1,58.00,2,No,55.0,1,58.80,Placed
1,M,79.33,1,78.33,0,2,77.48,2,Yes,86.5,0,66.28,Placed

In [37]:
data['workex'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [38]:
data['workex'] = data['workex'].map({'Yes':1,'No':0})

In [39]:
data.head(2)

,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status
0,M,67.00,0,91.00,0,1,58.00,2,0,55.0,1,58.80,Placed
1,M,79.33,1,78.33,0,2,77.48,2,1,86.5,0,66.28,Placed

In [40]:
data['status'].unique()

<StringArray>
['Placed', 'Not Placed']
Length: 2, dtype: str

In [41]:
data['status'] = data['status'].map({'Placed':1,'Not Placed':0})

In [42]:
data.head()

,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status
0,M,67.00,0,91.00,0,1,58.00,2,0,55.0,1,58.80,1
1,M,79.33,1,78.33,0,2,77.48,2,1,86.5,0,66.28,1
2,M,65.00,1,68.00,1,0,64.00,1,0,75.0,0,57.80,1
3,M,56.00,1,52.00,1,2,52.00,2,0,66.0,1,59.43,0
4,M,85.80,1,73.60,1,1,73.30,1,0,96.8,0,55.50,1

### 9. Store Feature Matrix In X and Response(Target) In Vector y

In [44]:
data.columns

Index(['gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s', 'degree_p',
       'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p', 'status'],
      dtype='str')

In [45]:
X = data.drop('status',axis=1)
y= data['status']

In [46]:
y

0      1
1      1
2      1
3      0
4      1
      ..
210    1
211    1
212    1
213    1
214    0
Name: status, Length: 215, dtype: int64

### 10. Splitting The Dataset Into The Training Set And Test Set

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

### 11. Import The models

In [49]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

### 12. Model Training

##### Pre-Training Validation: Ensure All Columns Are Numeric

In [50]:
# Safety check: catch any remaining string columns BEFORE model training
print('Final dtypes before training:')
print(X_train.dtypes)
string_cols = X_train.select_dtypes(include='object').columns.tolist()
if string_cols:
    raise ValueError(f'These columns are still strings and need encoding: {string_cols}')
else:
    print('\n✓ All columns are numeric. Safe to train!')

Final dtypes before training:
gender                str
ssc_p             float64
ssc_b               int64
hsc_p             float64
hsc_b               int64
hsc_s               int64
degree_p          float64
degree_t            int64
workex              int64
etest_p           float64
specialisation      int64
mba_p             float64
dtype: object

ValueError: These columns are still strings and need encoding: ['gender']

In [51]:
lr = LogisticRegression()
lr.fit(X_train,y_train)

svm = svm.SVC()
svm.fit(X_train,y_train)

knn=KNeighborsClassifier()
knn.fit(X_train,y_train)

dt=DecisionTreeClassifier()
dt.fit(X_train,y_train)

rf=RandomForestClassifier()
rf.fit(X_train,y_train)

gb=GradientBoostingClassifier()
gb.fit(X_train,y_train)

GradientBoostingClassifier()

### 13. Prediction on Test Data

In [52]:
y_pred1 = lr.predict(X_test)
y_pred2 = svm.predict(X_test)
y_pred3 = knn.predict(X_test)
y_pred4 = dt.predict(X_test)
y_pred5 = rf.predict(X_test)
y_pred6 = gb.predict(X_test)

### 14. Evaluating the Algorithms

In [53]:
from sklearn.metrics import accuracy_score

In [54]:
score1=accuracy_score(y_test,y_pred1)
score2=accuracy_score(y_test,y_pred2)
score3=accuracy_score(y_test,y_pred3)
score4=accuracy_score(y_test,y_pred4)
score5=accuracy_score(y_test,y_pred5)
score6=accuracy_score(y_test,y_pred6)

In [55]:
print(score1,score2,score3,score4,score5,score6)

0.8837209302325582 0.7674418604651163 0.7906976744186046 0.8372093023255814 0.7906976744186046 0.7906976744186046

In [56]:
final_data = pd.DataFrame({'Models':['LR','SVC','KNN','DT','RF','GB'],
            'ACC':[score1*100,
                  score2*100,
                  score3*100,
                  score4*100,
                  score5*100,score6*100]})

In [57]:
final_data

  Models        ACC
0     LR  88.372093
1    SVC  76.744186
2    KNN  79.069767
3     DT  83.720930
4     RF  79.069767
5     GB  79.069767

In [58]:
%pip install seaborn

In [59]:
import seaborn as sns

In [60]:
sns.barplot(data=final_data, x='Models', y='ACC')

<class 'TypeError'>: barplot() takes from 0 to 1 positional arguments but 2 were given

### 15. Prediction on New Data

In [61]:
# mba_p is OPTIONAL – pass None (or omit) to use the dataset mean
def predict_placement(gender, ssc_p, ssc_b, hsc_p, hsc_b, hsc_s,
                       degree_p, degree_t, workex, etest_p, specialisation,
                       mba_p=None):
    """Predict campus placement. mba_p defaults to dataset mean if not provided."""
    if mba_p is None:
        mba_p = MBA_P_MEAN
        print(f'mba_p not provided – using dataset mean: {mba_p}')
    new_data = pd.DataFrame({
        'gender': gender,
        'ssc_p': ssc_p,
        'ssc_b': ssc_b,
        'hsc_p': hsc_p,
        'hsc_b': hsc_b,
        'hsc_s': hsc_s,
        'degree_p': degree_p,
        'degree_t': degree_t,
        'workex': workex,
        'etest_p': etest_p,
        'specialisation': specialisation,
        'mba_p': mba_p,
    }, index=[0])
    return new_data

# Example 1: WITH mba_p provided
new_data = predict_placement(
    gender=0, ssc_p=67.0, ssc_b=0, hsc_p=91.0, hsc_b=0,
    hsc_s=1, degree_p=58.0, degree_t=2, workex=0,
    etest_p=55.0, specialisation=1, mba_p=58.8
)

# Example 2: WITHOUT mba_p (comment out Example 1 and uncomment below)
# new_data = predict_placement(
#     gender=0, ssc_p=67.0, ssc_b=0, hsc_p=91.0, hsc_b=0,
#     hsc_s=1, degree_p=58.0, degree_t=2, workex=0,
#     etest_p=55.0, specialisation=1   # mba_p omitted -> uses mean
# )

print(new_data)

In [62]:
# Compute mean mba_p from training data for use when it is not provided
MBA_P_MEAN = round(data['mba_p'].mean(), 2)
print(f'MBA percentage mean (used as default): {MBA_P_MEAN}')

lr= LogisticRegression()
lr.fit(X,y)

LogisticRegression()

In [63]:
p=lr.predict(new_data)
prob=lr.predict_proba(new_data)
if p==1:
    print('Placed')
    print(f"You will be placed with probability of {prob[0][1]:.2f}")
else:
    print("Not-placed")

Placed
,You will be placed with probability of 0.96

In [64]:
prob

array([[0.04186191, 0.95813809]])

### 16. Save Model Using Joblib

In [65]:
import joblib

In [66]:
joblib.dump(lr,'model_campus_placement')

['model_campus_placement']

In [67]:
model = joblib.load('model_campus_placement')

In [68]:
model.predict(new_data)

array([1], dtype=int64)

### GUI

In [69]:
import ipywidgets as widgets
from IPython.display import display, HTML
import joblib
import numpy as np
import pandas as pd

CSS = (
    "<link href='https://fonts.googleapis.com/css2?family=Sora:wght@300;400;600;700&display=swap' rel='stylesheet'>"
    "<style>"
    "#placement-app{font-family:'Sora',sans-serif;background:#0a0e1a;padding:8px 24px 32px;color:#e2e8f0}"
    ".app-header{text-align:center;margin-bottom:8px;padding-top:10px}"
    ".app-header::before{content:'';display:block;width:120px;height:3px;background:linear-gradient(90deg,#00d4ff,#7c3aed);margin:0 auto 10px;border-radius:2px}"
    ".app-title{font-size:2.1rem;font-weight:700;background:linear-gradient(135deg,#00d4ff,#a78bfa);-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;margin:0 0 4px}"
    ".app-subtitle{color:#64748b;font-size:0.88rem;font-weight:300;letter-spacing:.06em;text-transform:uppercase}"
    ".form-card{background:#111827;border:1px solid #1e2d45;border-radius:20px;padding:22px 26px 18px;max-width:900px;margin:0 auto 14px;position:relative;overflow:hidden}"
    ".form-card::before{content:'';position:absolute;top:0;left:0;right:0;height:2px;background:linear-gradient(90deg,#00d4ff,#7c3aed,transparent)}"
    ".section-title{font-size:.72rem;font-weight:600;letter-spacing:.16em;text-transform:uppercase;color:#00d4ff;margin:0 0 16px;display:flex;align-items:center;gap:12px}"
    ".section-title::after{content:'';flex:1;height:1px;background:#1e2d45}"
    ".form-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px 22px}"
    ".field-group{display:flex;flex-direction:column;gap:5px}"
    ".field-label{font-size:.72rem;font-weight:600;color:#94a3b8;letter-spacing:.08em;text-transform:uppercase}"
    ".optional-badge{display:inline-block;margin-left:7px;padding:1px 7px;border-radius:20px;background:rgba(124,58,237,.18);color:#a78bfa;font-size:.62rem;font-weight:600;letter-spacing:.06em;vertical-align:middle}"
    ".optional-hint{font-size:.75rem;color:#64748b;margin:0 auto 14px;padding:9px 14px;background:rgba(124,58,237,.07);border-left:3px solid rgba(124,58,237,.5);border-radius:0 8px 8px 0;max-width:900px}"
    ".result-card{max-width:900px;margin:0 auto;border-radius:20px;padding:30px;text-align:center;border:1px solid #1e2d45;animation:fadeIn .4s ease;font-family:'Sora',sans-serif}"
    ".result-placed{background:linear-gradient(135deg,rgba(16,185,129,.08),rgba(0,212,255,.06));border-color:rgba(16,185,129,.3)}"
    ".result-not-placed{background:linear-gradient(135deg,rgba(239,68,68,.08),rgba(124,58,237,.06));border-color:rgba(239,68,68,.3)}"
    ".result-icon{font-size:2.8rem;margin-bottom:8px}"
    ".result-label{font-size:.72rem;letter-spacing:.14em;text-transform:uppercase;color:#64748b;margin-bottom:8px}"
    ".result-verdict{font-size:1.9rem;font-weight:700;margin-bottom:10px}"
    ".verdict-placed{color:#10b981}.verdict-not-placed{color:#ef4444}"
    ".prob-bar-wrap{max-width:300px;margin:14px auto 0}"
    ".prob-label{display:flex;justify-content:space-between;font-size:.78rem;color:#64748b;margin-bottom:5px}"
    ".prob-bar-bg{background:rgba(255,255,255,.06);border-radius:99px;height:9px;overflow:hidden}"
    ".prob-bar-fill{height:100%;border-radius:99px;background:linear-gradient(90deg,#10b981,#00d4ff)}"
    ".mba-note{font-size:.75rem;color:#64748b;margin-top:10px}"
    "@keyframes fadeIn{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}"
    "</style>"
)
display(HTML(CSS))

# ── KEY FIX: style widgets directly via Python — CSS vars cannot reach widget DOM ──
W_LAYOUT = widgets.Layout(width='100%')
W_STYLE  = {'description_width': '0px'}

def make_dd(options, value=None):
    kw = dict(options=options, layout=W_LAYOUT, style=W_STYLE)
    if value is not None:
        kw['value'] = value
    return widgets.Dropdown(**kw)

def make_num(val=60.0):
    return widgets.BoundedFloatText(value=val, min=0, max=100, step=0.01,
                                    layout=W_LAYOUT, style=W_STYLE)

def make_txt(ph=''):
    return widgets.Text(value='', placeholder=ph, layout=W_LAYOUT, style=W_STYLE)

w_gender     = make_dd(['Female', 'Male'])
w_ssc_p      = make_num(60.0)
w_ssc_b      = make_dd(['Central', 'Others'])
w_hsc_p      = make_num(65.0)
w_hsc_b      = make_dd(['Central', 'Others'])
w_hsc_s      = make_dd(['Science', 'Commerce', 'Arts'])
w_degree_p   = make_num(65.0)
w_degree_t   = make_dd(['Sci&Tech', 'Comm&Mgmt', 'Others'])
w_workex     = make_dd(['No', 'Yes'])
w_etest_p    = make_num(60.0)
w_specialise = make_dd(['Not Applicable', 'Mkt&Fin', 'Mkt&HR'], value='Not Applicable')
w_mba_p      = make_txt('Leave blank to use dataset mean')

result_out = widgets.Output()

# ── Layout helpers ────────────────────────────────────────────────────────────
def render_section(heading, fields):
    display(HTML(f'<div class="form-card"><div class="section-title">{heading}</div><div class="form-grid">'))
    for label, w, opt in fields:
        badge = '<span class="optional-badge">Optional</span>' if opt else ''
        display(HTML(f'<div class="field-group"><div class="field-label">{label}{badge}</div>'))
        display(w)
        display(HTML('</div>'))
    display(HTML('</div></div>'))

display(HTML('<div id="placement-app">'))
display(HTML('<div class="app-header"><h1 class="app-title">Campus Placement Predictor</h1>'
             '<p class="app-subtitle">Machine Learning &middot; Logistic Regression &amp; Ensemble Models</p></div>'))

render_section('01 &nbsp; Academic Background', [
    ('Gender',               w_gender,     False),
    ('10th Grade % (SSC)',   w_ssc_p,      False),
    ('10th Board',           w_ssc_b,      False),
    ('12th Grade % (HSC)',   w_hsc_p,      False),
    ('12th Board',           w_hsc_b,      False),
    ('12th Specialisation',  w_hsc_s,      False),
])

render_section('02 &nbsp; Degree &amp; Work Profile', [
    ('Degree %',             w_degree_p,   False),
    ('Degree Type',          w_degree_t,   False),
    ('Work Experience',      w_workex,     False),
    ('Employability Test %', w_etest_p,    False),
])

render_section('03 &nbsp; MBA Details', [
    ('MBA Specialisation',   w_specialise, True),
    ('MBA %',                w_mba_p,      True),
])

display(HTML('<div class="optional-hint">&#x1F4A1; MBA fields are optional — leave blank or select "Not Applicable" to use dataset mean.</div>'))

# Predict button — color set via Python property
btn = widgets.Button(
    description='Predict Placement',
    layout=widgets.Layout(width='100%', height='54px'),
)
btn.style.button_color = '#4f46e5'
btn.style.font_weight  = 'bold'

display(HTML('<div style="max-width:900px;margin:16px auto 20px">'))
display(btn)
display(HTML('</div>'))
display(result_out)
display(HTML('</div>'))

# ── Prediction logic ──────────────────────────────────────────────────────────
def on_predict(b):
    result_out.clear_output()
    with result_out:
        try:
            p1  = 1 if w_gender.value == 'Male' else 0
            p2  = float(w_ssc_p.value)
            p3  = 1 if w_ssc_b.value == 'Central' else 0
            p4  = float(w_hsc_p.value)
            p5  = 1 if w_hsc_b.value == 'Central' else 0
            p6  = {'Science': 2, 'Commerce': 1, 'Arts': 0}[w_hsc_s.value]
            p7  = float(w_degree_p.value)
            p8  = {'Sci&Tech': 2, 'Comm&Mgmt': 1, 'Others': 0}[w_degree_t.value]
            p9  = 1 if w_workex.value == 'Yes' else 0
            p10 = float(w_etest_p.value)

            spec_note = ''
            if w_specialise.value == 'Not Applicable':
                p11 = round(data['specialisation'].mean())
                spec_note = 'MBA Specialisation not provided — using dataset default'
            else:
                p11 = 1 if w_specialise.value == 'Mkt&HR' else 0

            mba_note = ''
            mba_raw = w_mba_p.value.strip()
            if mba_raw == '':
                p12 = MBA_P_MEAN
                mba_note = f'MBA % not entered — using dataset mean: {MBA_P_MEAN:.2f}'
            else:
                p12 = float(mba_raw)

            model    = joblib.load('model_campus_placement')
            new_data = pd.DataFrame({
                'gender': p1, 'ssc_p': p2, 'ssc_b': p3, 'hsc_p': p4,
                'hsc_b': p5, 'hsc_s': p6, 'degree_p': p7, 'degree_t': p8,
                'workex': p9, 'etest_p': p10, 'specialisation': p11, 'mba_p': p12,
            }, index=[0])

            pred  = model.predict(new_data)[0]
            proba = model.predict_proba(new_data)[0]

            notes = ''.join(f'<div class="mba-note">&#x2139;&#xFE0F; {n}</div>'
                            for n in [spec_note, mba_note] if n)

            if pred == 1:
                pct = round(proba[1] * 100, 1)
                display(HTML(
                    f'<div class="result-card result-placed">'
                    f'<div class="result-icon">&#x1F393;</div>'
                    f'<div class="result-label">Prediction Result</div>'
                    f'<div class="result-verdict verdict-placed">Likely to be Placed</div>'
                    f'<div class="prob-bar-wrap">'
                    f'<div class="prob-label"><span>Placement Probability</span><span>{pct}%</span></div>'
                    f'<div class="prob-bar-bg"><div class="prob-bar-fill" style="width:{pct}%"></div></div>'
                    f'</div>{notes}</div>'
                ))
            else:
                display(HTML(
                    f'<div class="result-card result-not-placed">'
                    f'<div class="result-icon">&#x1F4CB;</div>'
                    f'<div class="result-label">Prediction Result</div>'
                    f'<div class="result-verdict verdict-not-placed">Not Likely to be Placed</div>'
                    f'<p style="color:#64748b;font-size:.9rem;margin-top:10px">'
                    f'Consider strengthening your profile and re-evaluating key metrics.</p>'
                    f'{notes}</div>'
                ))

        except Exception as ex:
            display(HTML(
                f'<div class="result-card" style="border-color:#ef4444;background:rgba(239,68,68,.07)">'
                f'<div class="result-icon">&#x26A0;&#xFE0F;</div>'
                f'<p style="color:#ef4444">Error: {ex}</p></div>'
            ))

btn.on_click(on_predict)